### ISSUE TITLE
Deployment via gh-pages

### ISSUE THREAD

**Issue by iepur1lla** [iepur1lla/awesome-portfolio.com#6]
We need to have a deployment for the website. The CNAME has been added already. The A records at cloudflare are pointing at github. We have to do the following:

* Add gh-pages to this project
* On npm run build: gatsby build should run and deploy to the gh-pages branch.

**Comment by mkam039** [comment]
I don't have access to repository settings!

**Comment by iepur1lla** [comment]
@mkam039: done and will give you access.
